--** generated by customers.py **--

CREATE EXTENSION IF NOT EXISTS plpython3u;

DROP SCHEMA IF EXISTS sch CASCADE;

DROP DOMAIN IF EXISTS sch.GenericText CASCADE;
DROP DOMAIN IF EXISTS sch.CustomerSymbol CASCADE;
DROP DOMAIN IF EXISTS sch.StreetName CASCADE;
DROP DOMAIN IF EXISTS sch.BuildingNo CASCADE;
DROP DOMAIN IF EXISTS sch.ApartmentNo CASCADE;
DROP DOMAIN IF EXISTS sch.ZipCode CASCADE;
DROP DOMAIN IF EXISTS sch.CityName CASCADE;
DROP DOMAIN IF EXISTS sch.CountryCode CASCADE;
DROP DOMAIN IF EXISTS sch.CountryName CASCADE;
DROP TYPE IF EXISTS sch.Country_t CASCADE;
DROP TYPE IF EXISTS sch.Address_t CASCADE;

CREATE SCHEMA IF NOT EXISTS sch;

CREATE DOMAIN sch.GenericText AS TEXT;


CREATE DOMAIN sch.CustomerSymbol AS VARCHAR(20);


CREATE DOMAIN sch.StreetName AS VARCHAR(200);


CREATE DOMAIN sch.BuildingNo AS VARCHAR(20);


CREATE DOMAIN sch.ApartmentNo AS VARCHAR(20);


CREATE DOMAIN sch.ZipCode AS VARCHAR(15);


CREATE DOMAIN sch.CityName AS VARCHAR(100);


CREATE DOMAIN sch.CountryCode AS CHAR(2);


CREATE DOMAIN sch.CountryName AS VARCHAR(100);


CREATE OR REPLACE FUNCTION sch.valid_customer_symbol_format(value VARCHAR(20))
RETURNS BOOLEAN AS $plpython$
    # only digits letters and - [ ]
    from re import fullmatch
    return fullmatch(r'[0-9a-zA-z\-\[\]]{10,20}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.CustomerSymbol ADD CONSTRAINT ck__sch__valid_customer_symbol_format
    CHECK (sch.valid_customer_symbol_format(VALUE));

CREATE OR REPLACE FUNCTION sch.valid_customer_symbol_first_char(value VARCHAR(20))
RETURNS BOOLEAN AS $plpython$
    # first char letter or cipher
    return 'a' <= value[0] <= 'z' or 'A' <= value[0] <= 'Z' or '0' <= value[0] <= '9'
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.CustomerSymbol ADD CONSTRAINT ck__sch__valid_customer_symbol_first_char
    CHECK (sch.valid_customer_symbol_first_char(VALUE));


CREATE OR REPLACE FUNCTION sch.valid_street_name(value VARCHAR(200))
RETURNS BOOLEAN AS $plpython$
    # without special characters
    from re import fullmatch
    return fullmatch(r'[ \S]{3,200}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.StreetName ADD CONSTRAINT ck__sch__valid_street_name
    CHECK (sch.valid_street_name(VALUE));


CREATE OR REPLACE FUNCTION sch.valid_building_no(value VARCHAR(20))
RETURNS BOOLEAN AS $plpython$
    # without special characters
    from re import fullmatch
    return fullmatch(r'[ \S]{,20}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.BuildingNo ADD CONSTRAINT ck__sch__valid_building_no
    CHECK (sch.valid_building_no(VALUE));


CREATE OR REPLACE FUNCTION sch.valid_apartment_no(value VARCHAR(20))
RETURNS BOOLEAN AS $plpython$
    # without special characters
    from re import fullmatch
    return fullmatch(r'[ \S]{,20}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.ApartmentNo ADD CONSTRAINT ck__sch__valid_apartment_no
    CHECK (sch.valid_apartment_no(VALUE));


CREATE OR REPLACE FUNCTION sch.valid_zip_code(value VARCHAR(15))
RETURNS BOOLEAN AS $plpython$
    # without special characters
    from re import fullmatch
    return fullmatch(r'[ \S]{2,15}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.ZipCode ADD CONSTRAINT ck__sch__valid_zip_code
    CHECK (sch.valid_zip_code(VALUE));


CREATE OR REPLACE FUNCTION sch.valid_city_name(value VARCHAR(100))
RETURNS BOOLEAN AS $plpython$
    # without special characters
    from re import fullmatch
    return fullmatch(r'[ \S]{3,100}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.CityName ADD CONSTRAINT ck__sch__valid_city_name
    CHECK (sch.valid_city_name(VALUE));


CREATE OR REPLACE FUNCTION sch.valid_country_code(value CHAR(2))
RETURNS BOOLEAN AS $plpython$
    # two uppercase ascci letters
    from re import fullmatch
    return fullmatch(r'[A-Z]{2}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.CountryCode ADD CONSTRAINT ck__sch__valid_country_code
    CHECK (sch.valid_country_code(VALUE));


CREATE OR REPLACE FUNCTION sch.valid_country_name(value VARCHAR(100))
RETURNS BOOLEAN AS $plpython$
    # without special characters
    from re import fullmatch
    return fullmatch(r'[ \S]{2,100}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.CountryName ADD CONSTRAINT ck__sch__valid_country_name
    CHECK (sch.valid_country_name(VALUE));


CREATE TYPE sch.Country_t AS (
    code sch.CountryCode,
    name sch.CountryName
);

CREATE DOMAIN sch.Country AS sch.Country_t;

CREATE OR REPLACE FUNCTION sch.Country(
    code sch.CountryCode,
    name sch.CountryName
) RETURNS sch.Country AS $SQL$
    SELECT ROW(code, name);
$SQL$ LANGUAGE SQL IMMUTABLE;


CREATE TYPE sch.Address_t AS (
    street_name sch.StreetName,
    building_no sch.BuildingNo,
    apartment_no sch.ApartmentNo,
    zip_code sch.ZipCode,
    city_name sch.CityName,
    country sch.Country
);

CREATE DOMAIN sch.Address AS sch.Address_t;

CREATE OR REPLACE FUNCTION sch.Address(
    street_name sch.StreetName,
    building_no sch.BuildingNo,
    apartment_no sch.ApartmentNo,
    zip_code sch.ZipCode,
    city_name sch.CityName,
    country sch.Country
) RETURNS sch.Address AS $SQL$
    SELECT ROW(street_name, building_no, apartment_no, zip_code, city_name, country);
$SQL$ LANGUAGE SQL IMMUTABLE;


CREATE OR REPLACE FUNCTION sch.valid_zip_code(self sch.Address_t)
RETURNS BOOLEAN AS $plpython$
    # zip code proper format
    import re
    return (
        re.fullmatch(r'[0-9]{2}-[0-9]{3}', self['zip_code']) is not None
        if self['country']['code'] == 'PL' else True
    )
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 

ALTER DOMAIN sch.Address ADD CONSTRAINT ck__sch__valid_zip_code
    CHECK (sch.valid_zip_code(VALUE));


SELECT sch.Country('PL', 'POLAND');
SELECT sch.Address('Dąb Rozwadowskiego', '6', '5', '00-902', 'Warszawa', sch.Country('PL', 'Polska'));

