--** generated by customers.py **--

CREATE EXTENSION IF NOT EXISTS plpython3u;

DROP DOMAIN IF EXISTS CustomerSymbol CASCADE;

CREATE DOMAIN CustomerSymbol AS VARCHAR(20);


CREATE OR REPLACE FUNCTION valid_customer_symbol_format(self VARCHAR(20))
RETURNS BOOLEAN AS $plpython$
    # only digits letters and - [ ]
    from re import fullmatch
    return fullmatch(r'[0-9a-zA-z\-\[\]]{10,20}', value) is not None
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 
--SECURITY DEFINER SET search_path = !TODO!, pg_temp;
--REVOKE ALL ON FUNCTION valid_customer_symbol_format FROM public;

ALTER DOMAIN CustomerSymbol ADD CONSTRAINT ck__valid_customer_symbol_format
    CHECK (valid_customer_symbol_format(VALUE));


CREATE OR REPLACE FUNCTION valid_other(self VARCHAR(20))
RETURNS BOOLEAN AS $plpython$
    # second validator test
    return not value.startswith('x')
$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; 
--SECURITY DEFINER SET search_path = !TODO!, pg_temp;
--REVOKE ALL ON FUNCTION valid_other FROM public;

ALTER DOMAIN CustomerSymbol ADD CONSTRAINT ck__valid_other
    CHECK (valid_other(VALUE));
