import typing
import types
import pydantic
import inspect
import functools
import dataclasses
import textwrap


@dataclasses.dataclass
class PGHint:
    type: str


type PredicateList[T] = list[tuple[typing.Callable[[T], bool], str]]

def field_validator[T](predicates: PredicateList[T], value: T):
    errors: list[str] = [msg for fun, msg in predicates if not fun(value)]
    if errors:
        raise ValueError('\n'.join(errors))
    return value


@dataclasses.dataclass
class PredicateInfo:
    name: str
    pgtype: str
    doc: str
    body: str

    @staticmethod
    def of(f: function, pgtype: str) -> PredicateInfo:
        
        doc: str | None = inspect.getdoc(f)
        if not doc:
            raise ValueError(f'Predicate must have docstring in [{f.__name__}]')
        
        body: str = inspect.getsource(typing.cast(typing.Any, f)).split(f'"""{doc}"""\n')[-1].strip('\n')
        if not body:
            raise ValueError(f'No body of predicate found [{f.__name__}]')
        
        return PredicateInfo(name=f.__name__, pgtype=pgtype, doc=doc, body=body)

    def sql_create(self) -> str:
        return '\n'.join([
            f"CREATE OR REPLACE FUNCTION {self.name}(self {self.pgtype})",
            f"RETURNS BOOLEAN AS $plpython$",
            f"{textwrap.indent(self.doc, '    # ')}",
            f"{self.body}",
            f"$plpython$ LANGUAGE plpython3u IMMUTABLE STRICT; ",
            f"--SECURITY DEFINER SET search_path = {'!TODO!'}, pg_temp;",
            f"--REVOKE ALL ON FUNCTION {self.name} FROM public;",
        ])


@dataclasses.dataclass
class ScalarInfo:
    name: str
    pgtype: str
    predicates: list[PredicateInfo]

    @staticmethod
    def of(name: str, annotated: typing.Any) -> ScalarInfo:
        validator: pydantic.AfterValidator = annotated.__metadata__[1]
        pghint: PGHint = annotated.__metadata__[2]

        return ScalarInfo(name=name, pgtype=pghint.type, predicates=[
            PredicateInfo.of(f, pghint.type)
            for f, __ in typing.cast(functools.partial[typing.Any], validator.func).args[0]
        ])
    
    def sql_create(self) -> str:
        return f'CREATE DOMAIN {self.name} AS {self.pgtype};'
    
    def sql_constraints(self) -> str:
        return '\n\n\n'.join([
            "\n".join([
                f"{p.sql_create()}",
                f"",
                f"ALTER DOMAIN {self.name} ADD CONSTRAINT ck__{p.name}",
                f"    CHECK ({p.name}(VALUE));",
            ])
            for p in self.predicates])


@dataclasses.dataclass
class ModuleInfo:
    scalars: list[ScalarInfo]

    @staticmethod
    def of(module: types.ModuleType) -> ModuleInfo:
        return ModuleInfo(
            scalars = [
                ScalarInfo.of(name, obj) 
                for name, obj in inspect.getmembers_static(module)
                if typing.get_origin(obj) is typing.Annotated and
                    len(obj.__metadata__) >= 3 and
                    isinstance(obj.__metadata__[0], pydantic.fields.FieldInfo) and
                    isinstance(obj.__metadata__[1], pydantic.AfterValidator) and
                    isinstance(obj.__metadata__[2], PGHint)],
        )

    
# predicates: exactly one arg named value, must have unique (in function text) one-line(for now) docstring in """ brackets
# scalars must be indpendent each other

def valid_customer_symbol_format(value: str) -> bool:
    """only digits letters and - [ ]"""
    from re import fullmatch
    return fullmatch(r'[0-9a-zA-z\-\[\]]{10,20}', value) is not None

def valid_other(value: str) -> bool:
    """second validator test"""
    return not value.startswith('x')

CustomerSymbol = typing.Annotated[
    str, 
    pydantic.Field(min_length=10, max_length=20, strict=True),
    pydantic.AfterValidator(functools.partial[str](field_validator, [
        (valid_customer_symbol_format, 'wrong input for customer symbol'), 
        (valid_other, 'second validator error'),
    ])),
    PGHint(type='VARCHAR(20)'),
]

import sys

mi: ModuleInfo = ModuleInfo.of(sys.modules[__name__])
sql = f"""--** generated by customers.py **--

CREATE EXTENSION IF NOT EXISTS plpython3u;

{'\n'.join([f"DROP DOMAIN IF EXISTS {s.name} CASCADE;" for s in mi.scalars])}

{'\n\n'.join([s.sql_create() for s in mi.scalars])}


{'\n\n'.join([s.sql_constraints() for s in mi.scalars])}
"""

with open(__file__.replace('.py', '-generated.sql'), 'w') as f:
    f.write(sql)
